controllers:
    resource: ../../Controller/
    type: annotation

oswis_org_oswis_web_page:
    controller: oswis_org_oswis_web.web_controller::showPage
    path: "/web/{slug}"

oswis_org_oswis_web_actualities:
    controller: oswis_org_oswis_web.web_controller::showWebActualities
    path: "/aktuality/{page?}/{limit?}"
    defaults:
        page: null
        limit: null

oswis_org_oswis_web_faq:
    controller: oswis_org_oswis_web.web_controller::showFaq
    path: "/faq"

oswis_org_oswis_rss:
    controller: oswis_org_oswis_web.rss_feed_controller::showRss
    path: "/rss/{limit}"

oswis_org_oswis_sitemap_xml:
    controller: oswis_org_oswis_web.site_map_controller::showSitemapXml
    path: "/sitemap.xml"

#oswis_org_oswis_sitemap:
#    controller: oswis_org_oswis_web.site_map_controller::showSitemap
#    path: "/sitemap"

