oswis_org_oswis_web_page:
    controller: oswis_org_oswis_web.web_controller::showPage
    path: "/web/{slug}"

oswis_org_oswis_web_actualities:
    controller: oswis_org_oswis_web.web_controller::showWebActualities
    path: "/aktuality/{pages?}/{limit?}"
    defaults:
        page: null
        limit: null

oswis_org_oswis_web_faq:
    controller: oswis_org_oswis_web.faq_web_controller::showFaq
    path: "/faq"
