##
## OswisWebBundle - Services configuration
## oswis-org/oswis-web-bundle/Resources/config/services.yaml
##
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ##
    ## Controllers wildcard (TODO: To be refactored. Do not use wildcards.)
    ##
    OswisOrg\OswisWebBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
        public: true

    ### Web controller
    oswis_org_oswis_web.web_controller:
        class: OswisOrg\OswisWebBundle\Controller\WebController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_web.web_service'
    OswisOrg\OswisWebBundle\Controller\WebController:
        alias: oswis_org_oswis_web.web_controller
        public: true

    ### Web service
    oswis_org_oswis_web.web_service:
        class: OswisOrg\OswisWebBundle\Service\WebService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisWebBundle\Service\WebService:
        alias: oswis_org_oswis_web.web_service
        public: true

    ### WebPage Service
    oswis_org_oswis_web.web_page_service:
        class: OswisOrg\OswisWebBundle\Service\WebPageService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisWebBundle\Service\WebPageService:
        alias: oswis_org_oswis_web.web_page_service
        public: true

    ### WebActuality Service
    oswis_org_oswis_web.web_actuality_service:
        class: OswisOrg\OswisWebBundle\Service\WebActualityService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisWebBundle\Service\WebActualityService:
        alias: oswis_org_oswis_web.web_actuality_service
        public: true
