##
## OswisWebBundle - Services configuration
## oswis-org/oswis-web-bundle/Resources/config/services.yaml
##
services:

    ### Web controller
    oswis_org_oswis_web.web_controller:
        class: OswisOrg\OswisWebBundle\Controller\WebController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_web.web_service'
            - '@oswis_org_oswis_web.faq_web_service'
    OswisOrg\OswisWebBundle\Controller\WebController:
        alias: oswis_org_oswis_web.web_controller
        public: true

    ### FAQ web controller
    oswis_org_oswis_web.faq_web_controller:
        class: OswisOrg\OswisWebBundle\Controller\FaqWebController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_web.faq_web_service'
    OswisOrg\OswisWebBundle\Controller\FaqWebController:
        alias: oswis_org_oswis_web.faq_web_controller
        public: true

    ### Web service
    oswis_org_oswis_web.web_service:
        class: OswisOrg\OswisWebBundle\Service\WebService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisWebBundle\Service\WebService:
        alias: oswis_org_oswis_web.web_service
        public: true

    ### FAQ web service
    oswis_org_oswis_web.faq_web_service:
        class: OswisOrg\OswisWebBundle\Service\FaqWebService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
    OswisOrg\OswisWebBundle\Service\FaqWebService:
        alias: oswis_org_oswis_web.faq_web_service
        public: true
