OswisOrg\OswisWebBundle\Entity\AbstractClass\AbstractWebPage:
    attributes:
        id:
            groups:
                - 'web_abstract_pages_get'
                - 'web_abstract_page_get'
        name:
            groups:
                - 'web_abstract_pages_get'
                - 'web_abstract_pages_post'
                - 'web_abstract_page_get'
                - 'web_abstract_page_put'
        shortName:
            groups:
                - 'web_abstract_pages_get'
                - 'web_abstract_pages_post'
                - 'web_abstract_page_get'
                - 'web_abstract_page_put'
        slug:
            groups:
                - 'web_abstract_pages_get'
                - 'web_abstract_pages_post'
                - 'web_abstract_page_get'
        description:
            groups:
                - 'web_abstract_pages_get'
                - 'web_abstract_pages_post'
                - 'web_abstract_page_get'
                - 'web_abstract_page_put'
        dateTime:
            groups:
                - 'web_abstract_pages_get'
                - 'web_abstract_pages_post'
                - 'web_abstract_page_get'
                - 'web_abstract_page_put'
        startDateTime:
            groups:
                - 'web_abstract_pages_get'
                - 'web_abstract_pages_post'
                - 'web_abstract_page_get'
                - 'web_abstract_page_put'
        endDateTime:
            groups:
                - 'web_abstract_pages_get'
                - 'web_abstract_pages_post'
                - 'web_abstract_page_get'
                - 'web_abstract_page_put'
        priority:
            groups:
                - 'web_abstract_pages_get'
                - 'web_abstract_pages_post'
                - 'web_abstract_page_get'
                - 'web_abstract_page_put'
        textValue:
            groups:
                - 'web_abstract_pages_get'
                - 'web_abstract_pages_post'
                - 'web_abstract_page_get'
                - 'web_abstract_page_put'

